stream redirector wip
superfluid-finance/protocol-monorepo pull request #1008
Opened 2022-08-02 14:30 UTC by 0xdavinchee

2022-08-03 13:17 UTC, 0xdavinchee commented on packages/ethereum-contracts/contracts/superfluid/Superfluid.sol
> +        if (isApp(ISuperApp(context.msgSender)) && context.appCallbackLevel >= MAX_APP_CALLBACK_LEVEL) {
Logic Change A

2022-08-03 13:17 UTC, 0xdavinchee commented on packages/ethereum-contracts/contracts/superfluid/Superfluid.sol
> -        bytes memory  ctx = _updateContext(Context({
Logic Change B

2022-08-03 13:17 UTC, 0xdavinchee commented on packages/ethereum-contracts/contracts/superfluid/Superfluid.sol
> -            appLevel: isApp(ISuperApp(msgSender)) ? 1 : 0,
Logic Change C

2022-08-03 13:17 UTC, 0xdavinchee commented on packages/ethereum-contracts/contracts/superfluid/Superfluid.sol
> -        if (isApp(ISuperApp(context.msgSender))) {
Logic Change A

2022-08-03 13:20 UTC, 0xdavinchee commented
Reason for foundry change: https://github.com/foundry-rs/foundry/issues/2572

2022-08-05 07:51 UTC, hellwolf commented
@d10r please have a look of this.

2022-08-10 08:29 UTC, d10r requested changes

2022-08-10 08:29 UTC, d10r commented on packages/ethereum-contracts/contracts/interfaces/superfluid/ISuperfluid.sol
> +     * @custom:modifiers
I'm afraid removing those trailing whitespaces after natspec tags will affect the documentation - last I tried the parser wouldn't recognize tags immediately followed by a newline.
I guess this was done automatically by the IDE. Could we disable removal of trailing whitespaces in comment sections?

2022-08-10 08:29 UTC, d10r commented on packages/ethereum-contracts/contracts/mocks/StreamRedirector.sol
> +     * @param _superApp the targetted super app
typo in "targetted"

2022-08-10 08:29 UTC, d10r commented on packages/ethereum-contracts/test/contracts/agreements/ConstantFlowAgreementV1.test.js
> +        it("#4.30 SuperApp with permissions should be able to stream to itself (blue elephant)", async () => {
finally he made it into the code!

2022-08-10 08:29 UTC, d10r commented on packages/ethereum-contracts/contracts/superfluid/Superfluid.sol
> -        if (isApp(ISuperApp(context.msgSender))) {
Note to self: not clear why this check can now be skipped if appCallbackLevel < MAX_APP_CALLBACK_LEVEL.

2022-08-10 08:30 UTC, 0xdavinchee commented on packages/ethereum-contracts/test/contracts/agreements/ConstantFlowAgreementV1.test.js
> +        it("#4.30 SuperApp with permissions should be able to stream to itself (blue elephant)", async () => {
😉

2022-08-10 09:40 UTC, 0xdavinchee commented on packages/ethereum-contracts/contracts/interfaces/superfluid/ISuperfluid.sol
> +     * @custom:modifiers
undid these changes, my IDE automatically does this, but will disable my IDE from doing this

2022-08-10 13:10 UTC, JoshuaTrujillo15 requested changes, later dismissed
Callbacks allow arbitrary super tokens, this app can be forcibly jailed.

2022-08-11 09:16 UTC, 0xdavinchee commented
@d10r @JoshuaTrujillo15 reviews addressed

2022-08-11 09:51 UTC, d10r approved these changes

2022-08-11 11:51 UTC, hellwolf approved these changes
great stuff

2022-08-11 11:52 UTC, merged