[wip][subgraph] upcoming feature set for the subgraph
superfluid-finance/protocol-monorepo pull request #1889
Opened 2024-03-12 14:31 UTC by kasparkallas

**What?**
A non-production subgraph branch with all the upcoming features and bug fixes.

**Why?**
Will ease the integration testing with the SDKs and the user-facing products when we deploy the feature branch.

**Other**
Includes:
* https://github.com/superfluid-finance/protocol-monorepo/pull/1877
* https://github.com/superfluid-finance/protocol-monorepo/pull/1878

Will include:
* https://github.com/superfluid-finance/protocol-monorepo/tree/subgraph-gda-index
* https://github.com/superfluid-finance/protocol-monorepo/pull/1843

2024-03-25 09:38 UTC, kasparkallas commented on packages/subgraph/schema.graphql
> +    isNFTApproval: Boolean!
needs to be mapped in the sdk-core, checking

2024-03-25 09:38 UTC, kasparkallas commented on packages/subgraph/schema.graphql
>      totalAmountDistributedUntilUpdatedAt: BigInt!
it's preferrable to get this value from the RPC now for a pool member, but it's beneficial to write out how the new fields change the formula on the client-side though

2024-03-25 09:38 UTC, kasparkallas commented on packages/subgraph/src/mappings/superfluidPool.ts
> +    // @note TODO update the poolMember.perUnitFlowRate
some TODO's here

2024-03-25 15:43 UTC, 0xdavinchee commented on packages/subgraph/src/mappings/superfluidPool.ts
> +    // @note TODO update the poolMember.perUnitFlowRate
removed the TODO's, they were addressed

2024-03-25 16:44 UTC, d10r requested changes, later dismissed

2024-03-25 16:44 UTC, d10r commented on packages/subgraph/config/polygon-mainnet.json
I think this wasn't added on purpose, or was it?

2024-03-26 10:48 UTC, kasparkallas commented on packages/subgraph/config/polygon-mainnet.json
removed the mistakenly added files

2024-03-26 10:49 UTC, 0xdavinchee approved these changes
LGTM

2024-03-26 11:47 UTC, hellwolf commented on packages/subgraph/src/addresses.template.ts
> +export function getIsLocalIntegrationTesting(): boolean {
nitpicking here: `getIs...` is so meh :/ :)

2024-03-26 11:49 UTC, hellwolf approved these changes
Quality. Let's go.

2024-03-26 12:03 UTC, merged