[AUTOMATIONS-CONTRACT] Extended Vesting Scheduler Tests (no unsigned commits)
superfluid-finance/protocol-monorepo pull request #2002
Opened 2024-08-08 11:25 UTC by kasparkallas

Continuation of: https://github.com/superfluid-finance/protocol-monorepo/pull/1994

2024-08-08 11:26 UTC, hellwolf approved these changes

2024-09-03 09:09 UTC, hellwolf requested changes
I noticed some tests failing. I suspect some flaky fuzzing tests. I will look into it when I have time.

2024-09-16 08:06 UTC, 0xPilou requested changes
The stateful fuzz test seem to fail on some occassion. 
Also, the stateful fuzz test does not cover claimable schedules. 
Do you want me to add this ?

2024-09-17 11:34 UTC, hellwolf approved these changes

2024-09-17 11:34 UTC, 0xPilou approved these changes

2024-09-17 11:41 UTC, merged

2024-09-17 15:14 UTC, kasparkallas commented
After this PR, this is the test coverage output of `forge coverage`:
```
| File                                                                                                  | % Lines           | % Statements       | % Branches        | % Funcs           |
|-------------------------------------------------------------------------------------------------------|-------------------|--------------------|-------------------|-------------------|
| packages/automation-contracts/scheduler/contracts/VestingSchedulerV2.sol                              | 98.16% (160/163)  | 98.81% (249/252)   | 85.00% (68/80)    | 100.00% (30/30)   |
```

The lack of complete 100% coverage can be explained by having guard clauses for readability and defensive programming that never actually get hit.