SDK Core QueryHandler improvements (block filtering, _meta table querying, infinity paging)
superfluid-finance/protocol-monorepo pull request #706
Opened 2022-03-15 14:32 UTC by kasparkallas

## Why
In preparation for some SDK redux changes.

### Block filtering

On the Subgraph, every possible entity/event can be queried by block number:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/10894666/158397078-e6d0bc73-5376-455c-8f0d-1e9dbf40da4a.png">

This feature enables it for all the QueryHandlers.

**How to use?**
```ts
const {
    data: pagedEvents
} = sfSubgraph.useEventsQuery(
    {
        chainId: queryChainId,
        block: {
            number_gte: 25000000
        }
    }
);
``` 

### Meta table querying
This feature creates a QueryHandler for the Subgraph's default _meta table:

<img width="148" alt="image" src="https://user-images.githubusercontent.com/10894666/158398143-89cf2299-e2c8-41c0-b081-b8d45dc75f8a.png">

**How to use?**
```ts
const meta = new MetaQueryHandler().get({ block: { number: 250000 } });
``` 

### Infinity paging
Iterates all the possible pages on Subgraph and returns them as one result. Definitely something that can be used to shoot oneself in the foot. But nonetheless, I'd like to be able to declaratively tell in my code to "get all the possible results" and "not having all the results can mean error".

**How to use?**
```ts
const {
    data: pagedEvents
} = sfSubgraph.useEventsQuery(
    {
        chainId: queryChainId,
        pagination: {
            take: Infinity
        }
    }
);
```

2022-03-15 15:15 UTC, kasparkallas commented
- [ ] Reminder! Add info to the changelog.

2022-03-21 13:38 UTC, hellwolf requested changes

2022-03-21 13:38 UTC, hellwolf commented on packages/sdk-core/src/pagination.ts
> +export type InfinityPaging = {
rename to -> AllPages

2022-03-21 13:38 UTC, hellwolf commented on packages/sdk-core/src/pagination.ts
> +export type InfinityPaging = {
discussion had: maybe iterator API support for querying in the future.

2022-03-23 09:36 UTC, kasparkallas commented on packages/sdk-core/src/pagination.ts
> +export type InfinityPaging = {
Renamed to "AllPaging".

2022-03-23 10:37 UTC, 0xdavinchee approved these changes
looks good! lgtm 🚀

2022-03-23 10:39 UTC, hellwolf approved these changes
![image](https://user-images.githubusercontent.com/186660/159680949-363d4d94-8ed5-4e09-8557-1242d5f15132.png)

https://xkcd.com/706/

2022-03-23 11:01 UTC, merged