monogamous SETH, L2 config improvements
superfluid-finance/protocol-monorepo pull request #707
Opened 2022-03-15 21:01 UTC by d10r

* remove WETH support from SETH because it's error prone and we can't update if a network's WETH contract changes
* improve config of new L2s
* add L2 deployment addresses

2022-03-16 10:20 UTC, 0xdavinchee commented on packages/js-sdk/src/getConfig.js
> +                        "https://api.thegraph.com/subgraphs/name/superfluid-finance/protocol-v1-optimism-mainnet",
optimism-mainnet => optimism-main

2022-03-17 09:37 UTC, hellwolf commented
I will look into this too

2022-03-18 08:22 UTC, hellwolf commented on packages/ethereum-contracts/contracts/tokens/SETH.sol
> +    event TokenUpgraded(address indexed account, uint256 amount);
why these need to be defined? is it not part of ISETHCustom(ISuperToken) ?

2022-03-18 08:23 UTC, hellwolf requested changes
just one small question.

2022-03-18 08:54 UTC, hellwolf approved these changes

2022-03-18 08:54 UTC, merged