add hardhat implementation of Budget NFT example using new sdk
superfluid-finance/protocol-monorepo pull request #719
Opened 2022-03-21 21:07 UTC by ananya

2022-04-04 08:57 UTC, JoshuaTrujillo15 requested changes
# 2022-04-04

Code looks good, though I suggest removing the `scripts/deploy.ts` file, as it's just an example.

2022-04-05 17:53 UTC, ananya commented
updated

2022-04-05 22:32 UTC, saflamini approved these changes

2022-04-06 07:50 UTC, JoshuaTrujillo15 approved these changes

2022-04-06 07:50 UTC, merged