make events immutable + update some packages
superfluid-finance/protocol-monorepo pull request #730
Opened 2022-04-07 11:36 UTC by 0xdavinchee

2022-04-12 09:02 UTC, kasparkallas requested changes

2022-04-12 09:02 UTC, kasparkallas commented on packages/subgraph/schema.graphql
> +    id: Bytes!
This does not look right... ? The field is `Bytes` but it's actually a concatenated string.

2022-04-12 09:02 UTC, kasparkallas commented on packages/subgraph/schema.graphql
> +    id: Bytes!
Same here. "id" should always be "ID", no?

2022-04-12 09:02 UTC, kasparkallas commented on packages/subgraph/src/mappings/idav1.ts
> +    let tokenId = event.params.token;
Does not look like this is used?

2022-04-20 17:28 UTC, hellwolf commented
@msoni89 please also have a look

2022-04-22 08:22 UTC, msoni89 commented on packages/subgraph/src/mappingHelpers.ts
> +    if (tokenAddress.equals(ZERO_ADDRESS)) {
Please early return it, is possible

2022-04-26 07:39 UTC, 0xdavinchee commented on packages/subgraph/src/mappingHelpers.ts
> +    if (tokenAddress.equals(ZERO_ADDRESS)) {
done

2022-04-26 16:50 UTC, hellwolf commented
@kasparkallas @msoni89 please revisit

2022-04-26 19:37 UTC, kasparkallas approved these changes

2022-04-28 09:46 UTC, merged