Missing transfer events for liquidation
superfluid-finance/protocol-monorepo pull request #855
Opened 2022-05-25 10:04 UTC by 0xdavinchee

* EventsEmitter library created for emitting transfer events
* Used in `SuperfluidToken.sol` in `makeLiquidationPaymentsV2`
* Test behavior changed

2022-05-26 14:11 UTC, hellwolf commented on packages/ethereum-contracts/contracts/superfluid/SuperfluidToken.sol
>      function makeLiquidationPayoutsV2(
@d10r you had comments regarding this function before, now we refactored it, please review it again.

2022-05-26 14:51 UTC, d10r requested changes

2022-05-26 14:51 UTC, d10r commented on packages/ethereum-contracts/contracts/superfluid/SuperfluidToken.sol
> +            address rewardedAccount = useDefaultRewardAccount ? rewardAccount : liquidatorAccount;
This will reset the rewardAccount to the zero address in anarchy mode.
Also I suggest we don't shadow variables, but pick a different name. E.g. here it could be `actualRewardAccount`.

2022-05-26 14:51 UTC, d10r commented on packages/ethereum-contracts/contracts/superfluid/SuperfluidToken.sol
> +            _balances[targetAccount] = _balances[targetAccount] + targetAccountBalanceDelta;
operators `+=` and `-=` (should now exists according to the [docs](https://docs.soliditylang.org/en/v0.8.13/cheatsheet.html#order-of-precedence-of-operators)) would make this more readable

2022-05-26 14:56 UTC, 0xdavinchee commented on packages/ethereum-contracts/contracts/superfluid/SuperfluidToken.sol
> +            address rewardedAccount = useDefaultRewardAccount ? rewardAccount : liquidatorAccount;
haven't pushed some changes yet, but `rewardedAccount` => `rewardAmountReceiver`

Also, we should be safe here with regards to the rewardAccount not being the zero address, it is set above to liquidator account so rewardedAccount will just be liquidator account in that case.

2022-05-26 14:57 UTC, 0xdavinchee commented on packages/ethereum-contracts/contracts/superfluid/SuperfluidToken.sol
> +            _balances[targetAccount] = _balances[targetAccount] + targetAccountBalanceDelta;
agree, will make this change before pushing changes

2022-05-26 15:04 UTC, d10r commented on packages/ethereum-contracts/contracts/superfluid/SuperfluidToken.sol
> +            address rewardedAccount = useDefaultRewardAccount ? rewardAccount : liquidatorAccount;
you're right

2022-05-27 07:20 UTC, hellwolf commented
@0xdavinchee sdk-core test broken.

@d10r otherwise, is it alright now?

2022-05-27 07:40 UTC, 0xdavinchee commented
> @0xdavinchee sdk-core test broken.
> 
> @d10r otherwise, is it alright now?

SDK-Core tests are gonna be broken until feature matic endpoint is indexed

2022-05-27 08:39 UTC, d10r approved these changes

2022-05-30 09:07 UTC, hellwolf approved these changes
NICE

2022-05-30 09:30 UTC, merged